NAME=Team\ Database

SRC=src/main.cpp src/dialogs.cpp src/teamhandler.cpp src/teammember.cpp src/teamplayer.cpp src/teamleader.cpp
CPPFLAGS=--std=c++11 -g
INCLUDES=-I./include

all:
	g++ $(CPPFLAGS) $(INCLUDES) $(SRC) -o Team\ Database
