
NAME	= Cellular\ Phone\ Stock

CXX		= g++
SRC		= main.cpp CellularPhoneStock.cpp CellularPhone.cpp
CCFLAGS	= --std=c++11 -g

all:
	$(CXX) $(CCFLAGS) $(SRC) -o $(NAME)
clang:
	clang++ $(SRC) -o $(NAME)
